//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/brunobowden/dev/testscroll/Java/main/harrycheung/Car.java
//

#include "Car.h"
#include "java/lang/Long.h"

@implementation HarrycheungCar

- (instancetype)init {
  if (self = [super init]) {
    JavaLangLong *comment_out_assignment_to_avoid_crash;
    comment_out_assignment_to_avoid_crash = [JavaLangLong valueOfWithLong:JavaLangLong_MAX_VALUE];
  }
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Car", NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _HarrycheungCar = { "Car", "harrycheung", NULL, 0x11, 1, methods, 0, NULL, 0, NULL};
  return &_HarrycheungCar;
}

@end
