//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/brunobowden/dev/testscroll/Java/main/harrycheung/Car.java
//

#ifndef _HarrycheungCar_H_
#define _HarrycheungCar_H_

#import "JreEmulation.h"

@interface HarrycheungCar : NSObject {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void HarrycheungCar_init() {}

#endif // _HarrycheungCar_H_
